Repository CSC207-2023Y-UofT/course-project-tindar, pull requests merged in 2023-08, with the labels that each got.

#54 [Feature 9] One-on-one chat display without messages and updates to Message and Conversation
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/courseproject/tindar/ChatActivity.java
  app/src/main/java/com/courseproject/tindar/entities/Conversation.java
  app/src/main/java/com/courseproject/tindar/entities/Message.java
  app/src/main/java/com/courseproject/tindar/entities/MessageInterface.java
  app/src/main/res/drawable/baseline_arrow_back_32_white.xml
  app/src/main/res/drawable/baseline_send_32.xml
  app/src/main/res/layout/activity_chat.xml
Labels: enhancement

#84 [Feature 71] Implemented Conversation List Frontend Prototype
  app/build.gradle
  app/src/main/java/com/courseproject/tindar/ui/conversations/ConversationFragment.java
  app/src/main/java/com/courseproject/tindar/ui/conversations/MyConversationRecyclerViewAdapter.java
  app/src/main/java/com/courseproject/tindar/ui/conversations/placeholder/PlaceholderContent.java
  app/src/main/java/com/courseproject/tindar/usecases/conversations/ConversationResponseModel.java
  app/src/main/res/layout/fragment_conversation.xml
  app/src/main/res/layout/fragment_conversation_list.xml
  app/src/main/res/menu/activity_main_drawer.xml
  app/src/main/res/navigation/mobile_navigation.xml
  app/src/main/res/values/dimens.xml
Labels: enhancement

#112 Conversation transition into Chat
  app/src/main/java/com/courseproject/tindar/ui/conversationlist/ConversationListFragment.java
  app/src/main/java/com/courseproject/tindar/ui/conversationlist/MyConversationRecyclerViewAdapter.java
  app/src/main/res/values/ids.xml
Labels: enhancement

#103 [Task 14] adds Java doc for like list / match list
  app/src/main/java/com/courseproject/tindar/controllers/likelist/LikeListController.java
  app/src/main/java/com/courseproject/tindar/ds/DatabaseHelper.java
  app/src/main/java/com/courseproject/tindar/ui/matchlist/MatchListFragment.java
  app/src/main/java/com/courseproject/tindar/usecases/likelist/LikeListDsGateway.java
  app/src/main/java/com/courseproject/tindar/usecases/likelist/LikeListDsResponseModel.java
  app/src/main/java/com/courseproject/tindar/usecases/likelist/LikeListInputBoundary.java
  app/src/main/java/com/courseproject/tindar/usecases/likelist/LikeListInteractor.java
  app/src/main/java/com/courseproject/tindar/usecases/likelist/LikeListResponseModel.java
Labels: documentation

#129 [Task 26-1] Addressing warnings that I don't expect to break everything or resolve in a different PR
  app/src/main/java/com/courseproject/tindar/BlankNavViewModel.java
  app/src/main/java/com/courseproject/tindar/controllers/login/LoginController.java
  app/src/main/java/com/courseproject/tindar/entities/Conversation.java
  app/src/main/java/com/courseproject/tindar/entities/MessageModel.java
  app/src/main/java/com/courseproject/tindar/presenters/viewprofiles/ViewProfilesPresenter.java
  app/src/main/java/com/courseproject/tindar/ui/chat/ChatActivity.java
  app/src/main/java/com/courseproject/tindar/ui/chat/ChatRecyclerViewAdapter.java
  app/src/main/java/com/courseproject/tindar/ui/conversationlist/ConversationListFragment.java
  app/src/main/java/com/courseproject/tindar/ui/conversationlist/MyConversationRecyclerViewAdapter.java
  app/src/main/java/com/courseproject/tindar/ui/conversationlist/placeholder/PlaceholderContent.java
  app/src/main/java/com/courseproject/tindar/ui/home/HomeFragment.java
  app/src/main/java/com/courseproject/tindar/usecases/conversationlist/ConversationResponseModel.java
  app/src/main/java/com/courseproject/tindar/usecases/login/LoginDsGateway.java
  app/src/main/java/com/courseproject/tindar/usecases/userlist/UserListDsGateway.java
  app/src/main/java/com/courseproject/tindar/usecases/userlist/UserListInputBoundary.java
  app/src/main/res/drawable/text_background_rounded_corners.xml
  app/src/main/res/layout/activity_chat.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/nav_header_blank_nav.xml
  app/src/main/res/layout/popup_wrong_credentials.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
  app/src/test/java/com/courseproject/tindar/controllers/editaccount/EditAccountControllerUnitTest.java
  app/src/test/java/com/courseproject/tindar/controllers/editfilters/EditFiltersControllerUnitTest.java
  app/src/test/java/com/courseproject/tindar/controllers/editprofile/EditProfileControllerUnitTest.java
  app/src/test/java/com/courseproject/tindar/controllers/login/LoginControllerUnitTest.java
  app/src/test/java/com/courseproject/tindar/usecases/editaccount/EditAccountInteractorUnitTest.java
  app/src/test/java/com/courseproject/tindar/usecases/editfilters/EditFiltersInteractorUnitTest.java
  app/src/test/java/com/courseproject/tindar/usecases/editprofile/EditProfileInteractorUnitTest.java
  app/src/test/java/com/courseproject/tindar/usecases/likelist/LikeListInteractorUnitTest.java
  app/src/test/java/com/courseproject/tindar/usecases/login/LoginInteractorUnitTest.java
  app/src/test/java/com/courseproject/tindar/usecases/signup/SignUpInteractorUnitTest.java
Labels: tech debt

#131 Finishing databasehelper javadocs
  app/src/main/java/com/courseproject/tindar/ds/DatabaseHelper.java
Labels: documentation

#152 Convo backend fix + Unit Test for Interactor and Controller + minor changes for Convo Frontend
  app/src/androidTest/java/com/courseproject/tindar/ds/DatabaseHelperTest.java
  app/src/main/java/com/courseproject/tindar/BlankNavActivity.java
  app/src/main/java/com/courseproject/tindar/controllers/conversationlist/ConversationListController.java
  app/src/main/java/com/courseproject/tindar/ds/DatabaseHelper.java
  app/src/main/java/com/courseproject/tindar/ui/conversationlist/ConversationListFragment.java
  app/src/main/java/com/courseproject/tindar/ui/conversationlist/MyConversationRecyclerViewAdapter.java
  app/src/main/java/com/courseproject/tindar/ui/conversationlist/placeholder/PlaceholderContent.java
  app/src/main/java/com/courseproject/tindar/usecases/conversationlist/ConversationDsResponseModel.java
  app/src/main/java/com/courseproject/tindar/usecases/conversationlist/ConversationListDsGateway.java
  app/src/main/java/com/courseproject/tindar/usecases/conversationlist/ConversationListInputBoundary.java
  app/src/main/java/com/courseproject/tindar/usecases/conversationlist/ConversationListInteractor.java
  app/src/main/java/com/courseproject/tindar/usecases/conversationlist/ConversationResponseModel.java
  app/src/main/java/com/courseproject/tindar/usecases/likelist/LikeListDsGateway.java
  app/src/main/java/com/courseproject/tindar/usecases/likelist/LikeListInteractor.java
  app/src/main/java/com/courseproject/tindar/usecases/matchlist/MatchListDsGateway.java
  app/src/main/java/com/courseproject/tindar/usecases/matchlist/MatchListInteractor.java
  app/src/test/java/com/courseproject/tindar/controllers/conversationlist/ConversationListControllerUnitTest.java
  app/src/test/java/com/courseproject/tindar/usecases/conversationlist/ConversationListInteractorUnitTest.java
  app/src/test/java/com/courseproject/tindar/usecases/likelist/LikeListInteractorUnitTest.java
  app/src/test/java/com/courseproject/tindar/usecases/matchlist/MatchListInteractorUnitTest.java
Labels: enhancement

#155 [Feature 13, 50, and 75] One on one chat with database
  app/src/main/java/com/courseproject/tindar/BlankNavViewModel.java
  app/src/main/java/com/courseproject/tindar/ds/DatabaseHelper.java
  app/src/main/java/com/courseproject/tindar/entities/ConversationDsModel.java
  app/src/main/java/com/courseproject/tindar/entities/MessageModel.java
  app/src/main/java/com/courseproject/tindar/entities/TindarMessage.java
  app/src/main/java/com/courseproject/tindar/ui/chat/ChatActivity.java
  app/src/main/java/com/courseproject/tindar/ui/chat/ChatRecyclerViewAdapter.java
  app/src/main/java/com/courseproject/tindar/usecases/chat/ChatActivityController.java
  app/src/main/java/com/courseproject/tindar/usecases/chat/ChatDsGateway.java
  app/src/main/java/com/courseproject/tindar/usecases/chat/ChatInteractor.java
  app/src/main/java/com/courseproject/tindar/usecases/chat/ChatPresenter.java
  app/src/main/java/com/courseproject/tindar/usecases/chat/ChatRequestModel.java
Labels: enhancement

#160 [Task 17] Javadoc for convo list
  app/src/main/java/com/courseproject/tindar/controllers/conversationlist/ConversationListController.java
  app/src/main/java/com/courseproject/tindar/ui/conversationlist/ConversationListFragment.java
  app/src/main/java/com/courseproject/tindar/ui/conversationlist/MyConversationRecyclerViewAdapter.java
  app/src/main/java/com/courseproject/tindar/usecases/conversationlist/ConversationDsResponseModel.java
  app/src/main/java/com/courseproject/tindar/usecases/conversationlist/ConversationListDsGateway.java
  app/src/main/java/com/courseproject/tindar/usecases/conversationlist/ConversationListInputBoundary.java
  app/src/main/java/com/courseproject/tindar/usecases/conversationlist/ConversationListInteractor.java
  app/src/main/java/com/courseproject/tindar/usecases/conversationlist/ConversationMessageDsResponseModel.java
Labels: documentation

#161 [Task 26 and 35] Last of warning fixes
  app/src/main/java/com/courseproject/tindar/ui/chat/ChatActivity.java
  app/src/main/java/com/courseproject/tindar/ui/chat/ChatRecyclerViewAdapter.java
  app/src/main/java/com/courseproject/tindar/ui/conversationlist/ConversationListFragment.java
  app/src/main/java/com/courseproject/tindar/ui/conversationlist/MyConversationRecyclerViewAdapter.java
  app/src/main/res/drawable-mdpi/kermit.png
  app/src/main/res/drawable-mdpi/spongebob1.png
  app/src/main/res/drawable-mdpi/spongebob2.jpg
  app/src/main/res/drawable-mdpi/spongebob3.jpg
  app/src/main/res/drawable-mdpi/spongebob4.jpg
  app/src/main/res/drawable-mdpi/spongebob5.jpg
  app/src/main/res/layout/recycler_row_message_sent.xml
  app/src/test/java/com/courseproject/tindar/controllers/editprofile/EditProfileControllerUnitTest.java
  app/src/test/java/com/courseproject/tindar/controllers/viewprofile/ViewProfilesControllerUnitTest.java
  app/src/test/java/com/courseproject/tindar/usecases/conversationlist/ConversationListInteractorUnitTest.java
  app/src/test/java/com/courseproject/tindar/usecases/likelist/LikeListInteractorUnitTest.java
  app/src/test/java/com/courseproject/tindar/usecases/matchlist/MatchListInteractorUnitTest.java
  app/src/test/java/com/courseproject/tindar/usecases/viewprofile/ViewProfileInteractorUnitTest.java
Labels: tech debt

#158 [Task 25] README.md updates
  README.md
Labels: documentation
